version: '3.8'

services:
  server:
    build: .
    ports:
      - "3001:3001"
      - "9877:9877/udp"
      - "8081:8081"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  react-app:
    build: .
    command: npm start
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
